[run]
build = "npm run build"
test = "npm run test"
lint = "npm run lint"

[paths]
dist = "./build"
src = "./src"

[gptengineer-app]  # this namespace is used for gptengineer.app, we can use this for internal experiments
project_id = "b8b73a61-7420-474c-a704-6a0abde4a3ee"